### ISSUE TITLE
When reporting questions and describing an issue, typing n or s will begin the next question while still in the reporting window.

### ISSUE THREAD

**Issue by penwarlock** [qbreader/website#104] opened 2022-11-22 01:06 UTC
Hitting the space bar will also buzz in once the next question has begun. Only in multiplayer, as far as I've seen.

**Comment by geoffrey-wu** [comment] 2022-11-22 01:08
Thanks for the catch—duplicate of #85 but I'll get to it as soon as I can.

**Closed by geoffrey-wu** 2022-11-22 01:08 UTC
Labels: bug, duplicate
